[[redirects]]
  from = "/api/info.json"
  to = "https://openslide-demo.s3.dualstack.us-east-1.amazonaws.com/info.json"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
